//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CourseworkExcersise4PartA.Webref2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ComputerUnitSoap", Namespace="http://www.webserviceX.NET/")]
    public partial class ComputerUnit : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ChangeComputerUnitOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ComputerUnit() {
            this.Url = global::CourseworkExcersise4PartA.Properties.Settings.Default.CourseworkExcersise4PartA_Webref2_ComputerUnit;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ChangeComputerUnitCompletedEventHandler ChangeComputerUnitCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webserviceX.NET/ChangeComputerUnit", RequestNamespace="http://www.webserviceX.NET/", ResponseNamespace="http://www.webserviceX.NET/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double ChangeComputerUnit(double ComputerValue, Computers fromComputerUnit, Computers toComputerUnit) {
            object[] results = this.Invoke("ChangeComputerUnit", new object[] {
                        ComputerValue,
                        fromComputerUnit,
                        toComputerUnit});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeComputerUnitAsync(double ComputerValue, Computers fromComputerUnit, Computers toComputerUnit) {
            this.ChangeComputerUnitAsync(ComputerValue, fromComputerUnit, toComputerUnit, null);
        }
        
        /// <remarks/>
        public void ChangeComputerUnitAsync(double ComputerValue, Computers fromComputerUnit, Computers toComputerUnit, object userState) {
            if ((this.ChangeComputerUnitOperationCompleted == null)) {
                this.ChangeComputerUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeComputerUnitOperationCompleted);
            }
            this.InvokeAsync("ChangeComputerUnit", new object[] {
                        ComputerValue,
                        fromComputerUnit,
                        toComputerUnit}, this.ChangeComputerUnitOperationCompleted, userState);
        }
        
        private void OnChangeComputerUnitOperationCompleted(object arg) {
            if ((this.ChangeComputerUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeComputerUnitCompleted(this, new ChangeComputerUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webserviceX.NET/")]
    public enum Computers {
        
        /// <remarks/>
        Bit,
        
        /// <remarks/>
        Byte,
        
        /// <remarks/>
        Kilobyte,
        
        /// <remarks/>
        Megabyte,
        
        /// <remarks/>
        Gigabyte,
        
        /// <remarks/>
        Terabyte,
        
        /// <remarks/>
        Petabyte,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ChangeComputerUnitCompletedEventHandler(object sender, ChangeComputerUnitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeComputerUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeComputerUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591